spring:
  application:
    name: CatMarket
  docker:
    compose:
      enabled: false
  profiles:
    active: feature

  datasource:
    url: jdbc:postgresql://localhost:5432/catmarket_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        jdbc.batch_size: 15
        order_inserts: true
        order_updates: true
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lirSNkFQXPZxI8Yj
            client-secret: a9811c09a19740919ae57967e8b802168e70addd
            scope:
              - read:user,user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

      resourceserver:
        opaquetoken:
          introspection-uri: https://api.github.com/user
          client-id: Ov23lirSNkFQXPZxI8Yj
          client-secret: a9811c09a19740919ae57967e8b802168e70addd

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi/catmarket.yaml

logging:
  level:
    spring: debug

    org.springframework.security: debug
    org.springframework.security.web: debug
    org.springframework.security.oauth2: debug

    org.springframework.web: debug
    org.springframework.web.client: trace
    org.springframework.web.filter: trace
