spring:
  application:
    name: CatMarket
  docker:
    compose:
      enabled: false
  profiles:
    active: feature
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi/catmarket.yaml